### ISSUE TITLE
Prepare on release

### ISSUE THREAD

**Issue by wu-sheng** [opentracing-contrib/java-hprose#2]
@bensigelman , I am going to release this repo to opentracing-contrib. Do you have a handbook about it?

btw @andot

**Comment by andot** [comment]
the handbook of hprose for java is here:

https://github.com/hprose/hprose-java/wiki

but only have chinese version.

**Comment by wu-sheng** [comment]
@andot , 😝, handbook about releasing, just keep you in the loop. 
@bensigelman , don't be mislead.

**Comment by wu-sheng** [comment]
@bhs 

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project opentracing-hprose: Failed to deploy artifacts: Could not transfer artifact io.opentracing.contrib:opentracing-hprose:jar:1.0 from/to bintray (https://api.bintray.com/maven/opentracing/maven/opentracing-hprose/;publish=1): Failed to transfer file: https://api.bintray.com/maven/opentracing/maven/opentracing-hprose/;publish=1/io/opentracing/contrib/opentracing-hprose/1.0/opentracing-hprose-1.0.jar. Return code is: 401, ReasonPhrase: Unauthorized. -> [Help 1]

I think this depend on you. You need to create a package for me?

**Comment by wu-sheng** [comment]
@sjoerdtalsma @bhs I found this in ci log:
```shell
[Publishing] This build was not started by a tag, publishing snapshot
```

Is this right, when you push some codes into master?

**Comment by sjoerdtalsma** [comment]
@wu-sheng 
> Is this right, when you push some codes into master?

Yes, the default travis script tries to publish a snapshot version for a regular commit on the `master` branch if you didn't tag it with `release-x.y.z`. Commits on other branches (including pull requests) should not be published at all I think _but will be built by travis_.

**Comment by sjoerdtalsma** [comment]
The error probably means there's a problem with the bitbucket or sonatype credentials.
I'll see if I can take a look at your travis log if I can access it and can find some time this evening...

**Comment by sjoerdtalsma** [comment]
I don't think the version of your project should be `1.0` yet in the maven build.
The travis script will set it to `1.0.0` if you tag it with `release-1.0.0` and after it succeeds, it will commit the pom with the next development version (in this case `1.0.1-SNAPSHOT`).

Did you try setting maven version to a snapshot version (e.g. `0.0.1-SNAPSHOT` or similar) ?

**Comment by sjoerdtalsma** [comment]
Since the error comes from the deploy plugin and it tries to upload to bintray, please check your `BINTRAY_USER` and `BINTRAY_KEY` environment settings.
(currently defined in the `.travis.yml` file)

You also didn't create a bintray package yet as far as I can tell. There should be a `opentracing-hprose` maven package on bintray for you to upload to.

(Please take care of #5 first)

**Comment by sjoerdtalsma** [comment]
_Update:_ Bintray upload now works.

Maven central sync failed on the 0.1.0 release because (message in bintray package):
>Last Sync Errors: Invalid POM: /io/opentracing/contrib/opentracing-hprose/0.1.0/opentracing-hprose-0.1.0.pom: Project name missing, Project description missing, Project URL missing Dropping existing partial staging repository.

So we need to add:
 - [x] Project name
 - [x] Project description
 - [x] Project URL

The maven error was less helpful:
>[ERROR] Failed to execute goal io.zipkin.centralsync-maven-plugin:centralsync-maven-plugin:0.1.0:sync (default-cli) on project opentracing-hprose: https://api.bintray.com/maven_central_sync/opentracing/maven/opentracing-hprose/versions/0.1.0 failed: Response{protocol=http/1.1, code=400, message=Bad Request, url=https://api.bintray.com/maven_central_sync/opentracing/maven/opentracing-hprose/versions/0.1.0} -> [Help 1]

**Comment by sjoerdtalsma** [comment]
Congratulations! :tada: 
You seem to have a `0.1.1` release in maven-central:
http://repo1.maven.org/maven2/io/opentracing/contrib/opentracing-hprose/0.1.1/

**Comment by wu-sheng** [comment]
@sjoerdtalsma Thanks for your time and help.

**Comment by sjoerdtalsma** [comment]
@wu-sheng You're welcome. I was glad there were people to help for my first release!
