### ISSUE TITLE
Set project version to snapshot in pom.xml

### ISSUE THREAD

**Issue by sjoerdtalsma** [opentracing-contrib/java-hprose#5]
I don't think the version of your project should be `1.0` yet in the maven build but something like `0.0.1-SNAPSHOT` instead.

The version should become a 'fixed' version only upon release:
1. The travis script will set the pom.xml version to `x.y.z` if you tag it with `release-x.y.z` and tags it with `x.y.z`.
2. This triggers yet another build on the master branch to perform the actual release.
3. After that release succeeds, it will change the pom to the next development version (e.g. `0.0.2-SNAPSHOT` after release `0.0.1`) and push to master.

**Comment by wu-sheng** [comment]
Done with SNAPSHOT suffix.

**Comment by wu-sheng** [comment]
Fail in snapshot and release tag.

- snapshot
```shell
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project opentracing-hprose: Failed to deploy artifacts: Could not transfer artifact io.opentracing.contrib:opentracing-hprose:jar:1.0.0-20170314.234325-1 from/to jfrog-snapshots (http://oss.jfrog.org/artifactory/oss-snapshot-local): Failed to transfer file: http://oss.jfrog.org/artifactory/oss-snapshot-local/io/opentracing/contrib/opentracing-hprose/1.0.0-SNAPSHOT/opentracing-hprose-1.0.0-20170314.234325-1.jar. Return code is: 401, ReasonPhrase: Unauthorized. -> [Help 1]
```

- release
```shell
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.5.3:prepare (default-cli) on project opentracing-hprose: Cannot prepare the release because you have local modifications :
[ERROR] [travis/publish.sh:modified]
```

I think the better choice to invite you as a collaborator. Invitation is sended.

**Comment by sjoerdtalsma** [comment]
Sorry, I wasn't very clear.
This is a separate issue from #2 and won't fix authentication problems in there.
That's why I created separate issues for this, so you can resolve them independently.

I'll accept the invite and see if I can help get the travis build working.
